version: "3.9"

services:
  wp-php:
    build: ./docker/php
    container_name: wp-php
    volumes:
      - ./wp:/var/www/domains/wp
    expose:
      - 9000
    networks:
      - wp-network

  wp-mysql:
    image: mysql:8.0
    container_name: wp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABSE: "${DB_DATABASE}"
    volumes:
      - wp-database:/var/lib/mysql
    expose:
      - 3306
    networks:
      - wp-network

  wp-nginx:
    image: nginx:1.27.0
    container_name: wp-nginx
    volumes:
      - ./wp:/var/www/domains/wp
      - ./docker/nginx:/etc/nginx/conf.d
    ports:
      - "127.0.0.1:8290:80"
    networks:
      - wp-network

  wp-adminer:
    image: adminer
    container_name: wp-adminer
    restart: always
    ports:
      - "127.0.0.1:8291:8080"
    networks:
      - wp-network
    environment:
      ADMINER_DESIGN: haeckel
      ADMINER_DEFAULT_SERVER: wp-mysql


networks:
  wp-network:
    driver: bridge

volumes:
  wp-database:
